# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('presentacion', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Bebida', 'A'), ('Botana', 'B')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('salario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Puesto')),
            ],
        ),
    ]
