# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('A', 'Bebida'), ('B', 'Botana')], max_length=1),
        ),
    ]
